### ISSUE TITLE
Can't import pyARD on Python 3.7

### ISSUE THREAD

**Issue by lgragert** [nmdp-bioinformatics/pyARD#9]
GenericMeta is not Python 3.7.

Traceback (most recent call last):
  File "ard_test.py", line 3, in <module>
    from pyard import ARD # NMDP allele codes
  File "/usr/local/lib/python3.7/site-packages/pyard/__init__.py", line 25, in <module>
    from .pyard import ARD
  File "/usr/local/lib/python3.7/site-packages/pyard/pyard.py", line 29, in <module>
    from .base_model_ import Model
  File "/usr/local/lib/python3.7/site-packages/pyard/base_model_.py", line 27, in <module>
    from .util import deserialize_model
  File "/usr/local/lib/python3.7/site-packages/pyard/util.py", line 27, in <module>
    from typing import GenericMeta
ImportError: cannot import name 'GenericMeta' from 'typing' (/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)

Some relevant links I found:

https://github.com/python/typing/issues/532

https://github.com/python/typing/issues/533

**Comment by lgragert** [comment]
The implementation of PEP560 led to the removal of GenericMeta.

https://www.python.org/dev/peps/pep-0560/

**Comment by mhalagan-nmdp** [comment]
PR #12 addressed this issue
